### PR TITLE
Portal frontend 5

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62)* status: all files reviewed, 8 unresolved discussions (waiting on @SKairinos)

___
*[`package.json` line 26 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7Dud4h3D6-VEfGZb3D:-O7Dud4h3D6-VEfGZb3E:bd6wwox) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/package.json#L26)):*
> ```JSON
>   ],
>   "dependencies": {
>     "codeforlife": "github:ocadotechnology/codeforlife-package-javascript#portal-frontend-5",
> ```

New package
___
*[`src/pages/privacyNotice/adults/Changes.tsx` line 9 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7Et6M092t4cMmu4Ixu:-O7Et6M12z34KG9TZs5n:b-kthmez) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/adults/Changes.tsx#L9)):*
> ```XML
>   <>
>     <Typography>
>       This Privacy Notice was last updated on 25th January 2023.
> ```

Wrong date. Ideally we have the last_updated date stored somewhere so we just change it in 1 spot and it updates it everywhere it's used.
___
*[`src/pages/privacyNotice/adults/ContactUs.tsx` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7EtKIs29ojkmX0ikjE:-O7EtKIs29ojkmX0ikjF:b-bfuimx) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/adults/ContactUs.tsx#L11)):*
> ```XML
>     <Typography mb={0}>
>       Please contact our Data Protection Officer or us at&nbsp;
>       <Link to="mailto:individualrights@ocado.com" target="_blank">
> ```

I don't think `target="_blank"` applies to `mailto` links
___
*[`src/pages/privacyNotice/adults/YourRights.tsx` line 64 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7EvFWy9eiW_-JYkRCc:-O7EvFWy9eiW_-JYkRCd:bf68xcn) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/adults/YourRights.tsx#L64)):*
> ```XML
>       <ListItemText>
>         email our Data Protection Officer at&nbsp;
>         <Link to="mailto:individualrights@ocado.com" target="_blank">
> ```

Same comment as before
___
*[`src/pages/privacyNotice/children/Children.tsx` line 42 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7EvZmSEcoz_WZ7g2Uq:-O7EvZmT7pr3oURmm0Mh:b-n79opn) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/children/Children.tsx#L42)):*
> ```XML
>       to identify you, such as your name and email address.
>     </Typography>
>     <TableOfContents
> ```

The children's version doesn't have a table of contents (I think that was done to make it less confusing for kids), we should probably remove it from here.
___
*[`src/pages/privacyNotice/children/HowToComplain.tsx` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7Ew3Js3EkBbi7H7ccL:-O7Ew3Js3EkBbi7H7ccM:b-ya81ng) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/children/HowToComplain.tsx#L12)):*
> ```XML
>       If you have a complaint about how we’ve used your personal information,
>       you can write to our Data Protection Officer at&nbsp;
>       <Link to="mailto:individualrights@ocado.com" target="_blank">
> ```

Same as above
___
*[`src/pages/privacyNotice/children/HowToComplain.tsx` line 23 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7EwAdI87xV0MtrhoJv:-O7EwAdJBWIgseQFI_5F:b-f48wud) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/children/HowToComplain.tsx#L23)):*
> ```XML
>       ICO by telephoning them on the number below or by visiting their website.
>     </Typography>
>     <Typography>Telephone: 0303 123 1113</Typography>
> ```

Update this to also have +44 like in the main adult notice
___
*[`src/pages/privacyNotice/children/YourRights.tsx` line 42 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7Ew_Vq2CS_ex1rpX_u:-O7Ew_Vq2CS_ex1rpX_v:b-ya81ng) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/children/YourRights.tsx#L42)):*
> ```XML
>       If you would like to use any of these rights listed above, please email
>       our Data Protection Officer at&nbsp;
>       <Link to="mailto:individualrights@ocado.com" target="_blank">
> ```

Same as above

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62)* status: 31 of 36 files reviewed, 8 unresolved discussions (waiting on @faucomte97)

___
*[`package.json` line 26 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7Dud4h3D6-VEfGZb3D:-O7ZkJuf5hcbWCrxYc6S:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/package.json#L26)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

New package
</blockquote></details>

Done.
___
*[`src/pages/privacyNotice/adults/Changes.tsx` line 9 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7Et6M092t4cMmu4Ixu:-O7ZlXvJ0KxC0xznnqZC:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/adults/Changes.tsx#L9)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Wrong date. Ideally we have the last_updated date stored somewhere so we just change it in 1 spot and it updates it everywhere it's used.
</blockquote></details>

Done.
___
*[`src/pages/privacyNotice/adults/ContactUs.tsx` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7EtKIs29ojkmX0ikjE:-O7Zj6Ro1npxNI7tcwr4:b-nu9cfp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/adults/ContactUs.tsx#L11)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I don't think `target="_blank"` applies to `mailto` links
</blockquote></details>

It does. It's a browser tab like any other.
___
*[`src/pages/privacyNotice/adults/YourRights.tsx` line 64 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7EvFWy9eiW_-JYkRCc:-O7ZjGDTDJjEvnwfrr6D:b-nu9cfp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/adults/YourRights.tsx#L64)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same comment as before
</blockquote></details>

It does. It's a browser tab like any other.
___
*[`src/pages/privacyNotice/children/Children.tsx` line 42 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7EvZmSEcoz_WZ7g2Uq:-O7ZjHuz2dk5YnsKwXyH:bkc3tso) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/children/Children.tsx#L42)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

The children's version doesn't have a table of contents (I think that was done to make it less confusing for kids), we should probably remove it from here.
</blockquote></details>

Got approval from Laura to add this on the 1st iteration of the portal-react.
___
*[`src/pages/privacyNotice/children/HowToComplain.tsx` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7Ew3Js3EkBbi7H7ccL:-O7ZjNNM-OgDl4_rL2Br:b-nu9cfp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/children/HowToComplain.tsx#L12)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

It does. It's a browser tab like any other.
___
*[`src/pages/privacyNotice/children/HowToComplain.tsx` line 23 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7EwAdI87xV0MtrhoJv:-O7ZjuJ1138RhbFouTys:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/children/HowToComplain.tsx#L23)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Update this to also have +44 like in the main adult notice
</blockquote></details>

Done.
___
*[`src/pages/privacyNotice/children/YourRights.tsx` line 42 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7Ew_Vq2CS_ex1rpX_u:-O7Zjy4U9A68AbmpEfVq:b-nu9cfp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/children/YourRights.tsx#L42)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

It does. It's a browser tab like any other.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62)* status: all files reviewed, 4 unresolved discussions (waiting on @SKairinos)

___
*[`src/pages/privacyNotice/adults/ContactUs.tsx` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7EtKIs29ojkmX0ikjE:-O7byPsq0-DrHPOanE5Q:bpi7n31) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/adults/ContactUs.tsx#L11)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

It does. It's a browser tab like any other.
</blockquote></details>

Is it? 
___
*[`src/pages/privacyNotice/children/HowToComplain.tsx` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-O7Ew3Js3EkBbi7H7ccL:-O7byGcH3La0elI67B6P:bpi7n31) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/e3d4aaf8ea60041742573640c4571a78a15df97b/src/pages/privacyNotice/children/HowToComplain.tsx#L12)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

It does. It's a browser tab like any other.
</blockquote></details>

Is it?

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/62#-:-O7cMDlOE4yPnL6OuujI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
