### PR TITLE
Email verification

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9)* status: all files reviewed, 5 unresolved discussions (waiting on @SKairinos)

___
*[`vite.config.ts` line 33 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9#-O1NAKQGEHuizM0VVj45:-O1NAKQGEHuizM0VVj46:b-oe0z2o) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/5ae4951afd5357a461da11260673f9035f5b9553/vite.config.ts#L33)):*
> ```XML
>       "@mui/x-date-pickers/AdapterDayjs",
>       "dayjs",
>       "dayjs/locale/en-gb",
> ```

Why were these added here?



_Code quote:_
```XML
      "@mui/x-date-pickers",
      "@mui/x-date-pickers/AdapterDayjs",
      "dayjs",
      "dayjs/locale/en-gb",
```
___
*[`src/images/paper_plane.png` line 0 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9#-O1N95-U2eqh0Ulljd8b:-O1N95-U2eqh0Ulljd8c:b-pamuwd) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/5ae4951afd5357a461da11260673f9035f5b9553/src/images/paper_plane.png#L0)):*
Are we able to use an icon instead of a PNG?
___
*[`src/images/sadface.png` line 0 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9#-O1N9AUx5w7es0v9-Pb5:-O1N9AUx5w7es0v9-Pb6:b-pamuwd) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/5ae4951afd5357a461da11260673f9035f5b9553/src/images/sadface.png#L0)):*
Are we able to use an icon instead of a PNG?
___
*[`src/pages/emailVerification/EmailVerification.tsx` line 42 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9#-O1N9fzr4rM_FCDAFXiM:-O1N9fzr4rM_FCDAFXiN:b-4nt41c) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/5ae4951afd5357a461da11260673f9035f5b9553/src/pages/emailVerification/EmailVerification.tsx#L42)):*
> ```XML
>               "An email has been sent to the address you provided.",
>               "Please follow the link within the email to verify your details. This will expire in 1 hour.",
>               "If you don't receive the email within the next few minutes, check your spam folder.",
> ```

This doesn't match what's currently on the website - happy to address later though if you want, as part of the whole styles / copy check.



_Code quote:_
```XML
              "An email has been sent to the address you provided.",
              "Please follow the link within the email to verify your details. This will expire in 1 hour.",
              "If you don't receive the email within the next few minutes, check your spam folder.",
```
___
*[`src/pages/emailVerification/Status.tsx` line 30 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9#-O1NAGj710piJK_re4yv:-O1NAGj710piJK_re4yw:bk5m7) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/5ae4951afd5357a461da11260673f9035f5b9553/src/pages/emailVerification/Status.tsx#L30)):*
> ```XML
>         ))}
>       </Stack>
>       <LinkButton to={paths._} style={{ marginTop: 30 }}>
> ```

Page seems to be missing the two buttons that redirect to Outlook and Gmail

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9)* status: all files reviewed, 5 unresolved discussions (waiting on @faucomte97 and @lauracumming)

___
*[`vite.config.ts` line 33 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9#-O1NAKQGEHuizM0VVj45:-O1NAlGO2LeuLHZ9fWF-:bgawvyt) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/5ae4951afd5357a461da11260673f9035f5b9553/vite.config.ts#L33)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why were these added here?
</blockquote></details>

Vite does not optimize these dependencies by default since they are only imported in the JS package. Yes, we import the JS package but vite doesn't look at what the JS package imports internally. Therefore, we need to manually inform vite to optimize these dependencies.
___
*[`src/images/paper_plane.png` line  at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9#-O1N95-U2eqh0Ulljd8b:-O1NBZu07zSU4TJe5oFa:b-tu1uwm) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/5ae4951afd5357a461da11260673f9035f5b9553/src/images/paper_plane.png#L)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Are we able to use an icon instead of a PNG?
</blockquote></details>

let's ask @lauracumming if we can use this instead
https://mui.com/material-ui/material-icons/?query=paper&selected=Send
___
*[`src/images/sadface.png` line  at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9#-O1N9AUx5w7es0v9-Pb5:-O1NBsTv7eWjLCrTw4Bd:bda6nlp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/5ae4951afd5357a461da11260673f9035f5b9553/src/images/sadface.png#L)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Are we able to use an icon instead of a PNG?
</blockquote></details>

let's ask @lauracumming if we can use this instead
https://mui.com/material-ui/material-icons/?query=sad&selected=SentimentVeryDissatisfied
___
*[`src/pages/emailVerification/Status.tsx` line 30 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9#-O1NAGj710piJK_re4yv:-O1NCX_WCfiRVGElc0cH:b-2gmjer) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/5ae4951afd5357a461da11260673f9035f5b9553/src/pages/emailVerification/Status.tsx#L30)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Page seems to be missing the two buttons that redirect to Outlook and Gmail
</blockquote></details>

Ah yes, forgot we added those.

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9)* status: 8 of 13 files reviewed, 4 unresolved discussions (waiting on @faucomte97 and @lauracumming)

___
*[`src/pages/emailVerification/EmailVerification.tsx` line 42 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9#-O1N9fzr4rM_FCDAFXiM:-O1agHV42viNF5EhY5j9:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/5ae4951afd5357a461da11260673f9035f5b9553/src/pages/emailVerification/EmailVerification.tsx#L42)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This doesn't match what's currently on the website - happy to address later though if you want, as part of the whole styles / copy check.
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

___
*[`src/images/paper_plane.png` line  at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9#-O1N95-U2eqh0Ulljd8b:-O1apIEX3dYXx5UmmxAN:b-tt0qck) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/5ae4951afd5357a461da11260673f9035f5b9553/src/images/paper_plane.png#L)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

let's ask @lauracumming if we can use this instead
https://mui.com/material-ui/material-icons/?query=paper&selected=Send
</blockquote></details>

Please delete
___
*[`src/images/sadface.png` line  at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9#-O1N9AUx5w7es0v9-Pb5:-O1apMkM7K-euN0ZMHiT:b-tt0qck) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/5ae4951afd5357a461da11260673f9035f5b9553/src/images/sadface.png#L)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

let's ask @lauracumming if we can use this instead
https://mui.com/material-ui/material-icons/?query=sad&selected=SentimentVeryDissatisfied
</blockquote></details>

Please delete

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9)* status: all files reviewed, 1 unresolved discussion (waiting on @lauracumming)

**Review by faucomte97 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
