### PR TITLE
Add footer

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35)

### CODE REVIEW

**Comment by SKairinos** [comment]
*[`src/features/footer/Footer.tsx` line 22 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n7Pku2Lu10p7faRaN:-O5n7Pku2Lu10p7faRaO:b-nldtz4) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Footer.tsx#L22)):*
> ```XML
> export interface FooterProps {}
> 
> const Footer: FC<FooterProps> = () => {
> ```

In src/App.tsx, set the footer prop to be this component.

```ts
footer={<Footer />}
```

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35)* status: all files reviewed, 16 unresolved discussions (waiting on @faucomte97)

___
*[`src/api/user.ts` line 70 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5mxiOe7vqakMx2J7lp:-O5mxiOf9fE5AFxju3ve:b3w2s00) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/api/user.ts#L70)):*
> ```XML
> 
> export type RegisterToNewsletterResult = null
> export type RegisterToNewsletterArg = { email: string }
> ```

Arg<User, "email">



_Code quote:_
```XML
{ email: string }
```
___
*[`src/features/footer/Links.tsx` line 13 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n00PT1kxw5PbnEqk9:-O5n00PT1kxw5PbnEqkA:btdvc4q) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Links.tsx#L13)):*
> ```XML
> 
> const FooterLink: FC<{
>   href: string
> ```

rename prop to `to`
___
*[`src/features/footer/Links.tsx` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n05fKBs1X2rTo8x79:-O5n05fKBs1X2rTo8x7A:boctvmu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Links.tsx#L14)):*
> ```XML
> const FooterLink: FC<{
>   href: string
>   text: string
> ```

rename prop to `children`
___
*[`src/features/footer/Links.tsx` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n3i-HB-8NKP8SZFwW:-O5n3i-I-eaF0Hz4v3bm:b-g4jmow) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Links.tsx#L15)):*
> ```XML
>   href: string
>   text: string
>   external?: boolean
> ```

rename this prop to `newTab`. You're using this to open links in new browser tabs.
___
*[`src/features/footer/Links.tsx` line 21 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n0lXe6Etssh_65002:-O5n0lXe6Etssh_65003:b-oqpt0f) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Links.tsx#L21)):*
> ```XML
>       to={href}
>       target={external ? "_blank" : "_self"}
>       sx={{
> ```

create a global var
```ts
import { SxProps } from "@mui/material"
...
const LINK_STYLE: SxProps = {...}
...
sx={LINK_STYLE}
``` 
___
*[`src/features/footer/Links.tsx` line 47 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n0cjZ5GbIvcL-RoLS:-O5n0cjZ5GbIvcL-RoLT:bly1ev) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Links.tsx#L47)):*
> ```XML
>       <Grid xs={12} sm={4}>
>         <Stack spacing={1}>
>           <FooterLink href={paths.aboutUs._} text={"About us"} />
> ```

<FooterLink href={paths.aboutUs._}>
About us
</FooterLink>



_Code quote:_
```XML
<FooterLink href={paths.aboutUs._} text={"About us"} />
```
___
*[`src/features/footer/Links.tsx` line 50 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n2vB94kuD-6AOUbw0:-O5n2vB94kuD-6AOUbw1:b-d4sq6v) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Links.tsx#L50)):*
> ```XML
>           {/*TODO: Use Freshdesk hook*/}
>           <MuiLink
>             sx={{
> ```

sx={LINK_STYLE}
___
*[`src/features/footer/Links.tsx` line 72 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n2vgLAuTlukQft0P6:-O5n2vgLAuTlukQft0P7:b-d4sq6v) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Links.tsx#L72)):*
> ```XML
>           {/*TODO: Use OneTrust banner hook*/}
>           <MuiLink
>             sx={{
> ```

sx={LINK_STYLE}
___
*[`src/features/footer/NewsletterSignUp.tsx` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n4TQRClatydKEyrri:-O5n4TQRClatydKEyrrj:b-io2enx) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/NewsletterSignUp.tsx#L11)):*
> ```XML
> export interface NewsletterSignUpProps {}
> 
> const NewsletterSignUp: FC<NewsletterSignUpProps> = () => {
> ```

rename to RegisterToNewsletterForm



_Code quote:_
```XML
 NewsletterSignUp
```
___
*[`src/features/footer/NewsletterSignUp.tsx` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n4gbj0-DiH48KUxD9:-O5n4gbj0-DiH48KUxDA:bvtpy32) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/NewsletterSignUp.tsx#L12)):*
> ```XML
> 
> const NewsletterSignUp: FC<NewsletterSignUpProps> = () => {
>   const theme = useTheme()
> ```

delete this
___
*[`src/features/footer/NewsletterSignUp.tsx` line 13 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n4ipmDcb6fzNEfEOC:-O5n4ipmDcb6fzNEfEOD:bvtpy32) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/NewsletterSignUp.tsx#L13)):*
> ```XML
> const NewsletterSignUp: FC<NewsletterSignUpProps> = () => {
>   const theme = useTheme()
>   const onlyXS = useMediaQuery(theme.breakpoints.only("xs"))
> ```

delete this
___
*[`src/features/footer/NewsletterSignUp.tsx` line 77 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n4mpu5tDVmgs7OE9Q:-O5n4mpu5tDVmgs7OE9R:bpg0ytw) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/NewsletterSignUp.tsx#L77)):*
> ```XML
>               }}
>             />
>             <forms.SubmitButton sx={{ width: onlyXS ? "100%" : undefined }}>
> ```

sx={theme => ({ width: useMediaQuery(theme.breakpoints.only("xs")) ? "100%" : undefined })}
___
*[`src/features/footer/SocialMediaIcons.tsx` line 30 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n5U6L8RGiLWEb5ANj:-O5n5U6L8RGiLWEb5ANk:b-gl552y) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/SocialMediaIcons.tsx#L30)):*
> ```XML
> }> = ({ href, children }) => {
>   return (
>     <IconButton href={href} target="_blank" sx={{ padding: 0 }}>
> ```

use this component instead

import {LinkIconButton} from "codeforlife/components/router"
___
*[`src/features/footer/SocialMediaIcons.tsx` line 30 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n652_B5ITfkBjoXfS:-O5n652_B5ITfkBjoXfT:bfxcfic) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/SocialMediaIcons.tsx#L30)):*
> ```XML
> }> = ({ href, children }) => {
>   return (
>     <IconButton href={href} target="_blank" sx={{ padding: 0 }}>
> ```

to={to}



_Code quote:_
```XML
 href={href}
```
___
*[`src/features/footer/SocialMediaIcons.tsx` line 45 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n6Wl9D0ieVzoyxBFA:-O5n6Wl9D0ieVzoyxBFB:bs1s1ed) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/SocialMediaIcons.tsx#L45)):*
> ```XML
> const SocialMediaIcons: FC<SocialMediaIconsProps> = () => {
>   return (
>     <Grid container xs={12} order={{ xs: 1, md: 2 }}>
> ```

Delete this Grid. Also, the children of a grid container must always be a grid [item] (a grid that's not a container is an item). [See](https://mui.com/material-ui/react-grid2/#basic-grid)

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35)* status: all files reviewed, 16 unresolved discussions (waiting on @SKairinos)

___
*[`src/api/user.ts` line 70 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5mxiOe7vqakMx2J7lp:-O5wWsuGAHBi4l98ZnlQ:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/api/user.ts#L70)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Arg<User, "email">
</blockquote></details>

Done.
___
*[`src/features/footer/Footer.tsx` line 22 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n7Pku2Lu10p7faRaN:-O5wXOPG561QuFCcG25G:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Footer.tsx#L22)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

In src/App.tsx, set the footer prop to be this component.

```ts
footer={<Footer />}
```
</blockquote></details>

Done.
___
*[`src/features/footer/Links.tsx` line 13 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n00PT1kxw5PbnEqk9:-O5wXXwoDPRWwa9M7smO:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Links.tsx#L13)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rename prop to `to`
</blockquote></details>

Done.
___
*[`src/features/footer/Links.tsx` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n05fKBs1X2rTo8x79:-O5wXdy62uM9Dv846DN2:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Links.tsx#L14)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rename prop to `children`
</blockquote></details>

Done.
___
*[`src/features/footer/Links.tsx` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n3i-HB-8NKP8SZFwW:-O5wYJmB2pZSN1FNKKZU:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Links.tsx#L15)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rename this prop to `newTab`. You're using this to open links in new browser tabs.
</blockquote></details>

Done.
___
*[`src/features/footer/Links.tsx` line 21 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n0lXe6Etssh_65002:-O5wYhkUBghD-9PPi0w1:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Links.tsx#L21)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

create a global var
```ts
import { SxProps } from "@mui/material"
...
const LINK_STYLE: SxProps = {...}
...
sx={LINK_STYLE}
```
</blockquote></details>

Done.
___
*[`src/features/footer/Links.tsx` line 47 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n0cjZ5GbIvcL-RoLS:-O5wYiPa4CYppKcVGfLY:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Links.tsx#L47)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

<FooterLink href={paths.aboutUs._}>
About us
</FooterLink>
</blockquote></details>

Done.
___
*[`src/features/footer/Links.tsx` line 50 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n2vB94kuD-6AOUbw0:-O5wYrqhBPfvZdTz8eRS:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Links.tsx#L50)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

sx={LINK_STYLE}
</blockquote></details>

Done.
___
*[`src/features/footer/Links.tsx` line 72 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n2vgLAuTlukQft0P6:-O5wYsRO7mC_ml1KeacA:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/Links.tsx#L72)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

sx={LINK_STYLE}
</blockquote></details>

Done.
___
*[`src/features/footer/SocialMediaIcons.tsx` line 30 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n5U6L8RGiLWEb5ANj:-O5w_aa22F8Mj1AsgjAC:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/SocialMediaIcons.tsx#L30)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

use this component instead

import {LinkIconButton} from "codeforlife/components/router"
</blockquote></details>

Done.
___
*[`src/features/footer/SocialMediaIcons.tsx` line 30 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n652_B5ITfkBjoXfS:-O5w_egWBlMvIvNPTz6J:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/SocialMediaIcons.tsx#L30)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

to={to}
</blockquote></details>

Done.
___
*[`src/features/footer/SocialMediaIcons.tsx` line 45 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n6Wl9D0ieVzoyxBFA:-O5wa1c36BBOVILpNBPL:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/SocialMediaIcons.tsx#L45)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Delete this Grid. Also, the children of a grid container must always be a grid [item] (a grid that's not a container is an item). [See](https://mui.com/material-ui/react-grid2/#basic-grid)
</blockquote></details>

Done.
___
*[`src/features/footer/NewsletterSignUp.tsx` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n4TQRClatydKEyrri:-O5wZ1gY4zpxM-GHeQA9:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/NewsletterSignUp.tsx#L11)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rename to RegisterToNewsletterForm
</blockquote></details>

Done.
___
*[`src/features/footer/NewsletterSignUp.tsx` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n4gbj0-DiH48KUxD9:-O5waakc6zUHwdaJBbuU:b6umlo8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/NewsletterSignUp.tsx#L12)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

delete this
</blockquote></details>

cf comment below
___
*[`src/features/footer/NewsletterSignUp.tsx` line 13 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n4ipmDcb6fzNEfEOC:-O5wabaqChecCvxo2fzp:b6umlo8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/NewsletterSignUp.tsx#L13)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

delete this
</blockquote></details>

cf comment below
___
*[`src/features/footer/NewsletterSignUp.tsx` line 77 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35#-O5n4mpu5tDVmgs7OE9Q:-O5wa4r6Ckr6VLpVTVGY:b-vuga6m) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/cda681304f77e29b42d953cd7effe4aaa79aa99c/src/features/footer/NewsletterSignUp.tsx#L77)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

sx={theme => ({ width: useMediaQuery(theme.breakpoints.only("xs")) ? "100%" : undefined })}
</blockquote></details>

Couldn't do that, something about hooks not being callable from inside a callback. 

`ESLint: React Hook "useMediaQuery" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function.(react-hooks/ rules-of-hooks)`

**Review by SKairinos — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/35)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
