### PR TITLE
Portal frontend#19

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/22)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/22)* status: all files reviewed, 6 unresolved discussions (waiting on @SKairinos)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/22#-O3dckrY5xHvYok9gtQ7:-O3dckrY5xHvYok9gtQ8:b-jfoudj) (no related file):*
Install new JS package reminder

___

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/22)* status: 24 of 27 files reviewed, 6 unresolved discussions (waiting on @faucomte97)

___
*[`src/pages/teacherDashboard/school/School.tsx` line 78 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/22#-O3dYLfEDGIeBX_XTOKo:-O3fgyzC2_NXEIhW56to:b7b9osk) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/68b88dc794ea7c58411c3e3038fdef663d24e0bb/src/pages/teacherDashboard/school/School.tsx#L78)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Edge case: in the case where the teacher has already deleted all their classes, clicking that button simply removes the teacher from the school since there is no need to transfer classes.
The user is then automatically redirected to the onboarding where they need to create a school.

Edit: I just noticed the `!classes.length` check in the leave school page, does that check basically handle this edge case?
</blockquote></details>

Yes, exactly. When removing a teacher from a school, by default, we redirect them to the transfer classes page. The first thing the transfer classes page does is check if there are any classes to transfer. If there are no classes to transfer, the teacher will auto-leave the school.

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/22)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/22)* status: 26 of 27 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`src/pages/teacherDashboard/school/TransferClasses.tsx` line 74 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/22#-O3dbr47ECo3Y7VJxS_h:-O3gHBvl5VVPJrOr6js-:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/68b88dc794ea7c58411c3e3038fdef663d24e0bb/src/pages/teacherDashboard/school/TransferClasses.tsx#L74)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Not a big fan of this random "go back" link right after the heading. We also already have the cancel button below... Check with Laura maybe?
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/22#-:-O3gKJis8uCKmynxLQQx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
