### PR TITLE
api interface

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1)* status: 0 of 15 files reviewed, 1 unresolved discussion

___
*[`package.json` line 23 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1#-NzTKl_C7mmf1zGvJrUN:-NzTKl_C7mmf1zGvJrUO:bnbocvi) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/1563472445ae93616029ea583cf9c363f4c6faee/package.json#L23)):*
> ```JSON
>   "dependencies": {
>     "@reduxjs/toolkit": "^2.0.1",
>     "codeforlife": "github:ocadotechnology/codeforlife-package-javascript#fix_api_types",
> ```

install new version

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1)* status: 0 of 15 files reviewed, 2 unresolved discussions

___
*[`src/api/teacher.ts` line 33 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1#-NzTRcIe924Ahf9ruTdj:-NzTRcIe924Ahf9ruTdk:b5i22sw) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/1563472445ae93616029ea583cf9c363f4c6faee/src/api/teacher.ts#L33)):*
> ```XML
>     removeTeacherFromSchool: build.mutation<
>       UpdateResult<Teacher, "user">,
>       Teacher["id"]
> ```

UpdateArg<Teacher>

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 15 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1)* status: all files reviewed, 6 unresolved discussions (waiting on @SKairinos)

___
*[`src/api/klass.ts` line 26 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1#-NzYaUIoExwWY8Y6UpgI:-NzYaUIoExwWY8Y6UpgJ:b-6565k5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/f04ed30c1baa671798927d952f05400101f1118a/src/api/klass.ts#L26)):*
> ```XML
>         Class,
>         "name" | "read_classmates_data",
>         "teacher" | "receive_requests_until"
> ```

Wanted to double check if `receive_requests_until` is in fact a required arg for creating a class. It looks like it is in the serializer, but are we planning to require teachers to provide this setting when creating a class? Default value currently is just "never" / "off"
___
*[`src/api/schoolTeacherInvitation.ts` line 50 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1#-NzYpAnp0RWfUqatYwj1:-NzYpAnp0RWfUqatYwj2:b5m5a11) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/f04ed30c1baa671798927d952f05400101f1118a/src/api/schoolTeacherInvitation.ts#L50)):*
> ```XML
>     >({
>       query: ([id, body]) => ({
>         url: buildUrl(detailUrl, { url: { id } }),
> ```

add `/accept`
___
*[`src/api/schoolTeacherInvitation.ts` line 61 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1#-NzYpJks2RuQpFGWmEhe:-NzYpJks2RuQpFGWmEhf:b-rxmks2) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/f04ed30c1baa671798927d952f05400101f1118a/src/api/schoolTeacherInvitation.ts#L61)):*
> ```XML
>     >({
>       query: id => ({
>         url: buildUrl(detailUrl, { url: { id } }),
> ```

add `/reject`
___
*[`src/api/user.ts` line 52 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1#-NzYq_O_Cso7SKMQ5kAK:-NzYq_O_Cso7SKMQ5kAL:bwuvwqv) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/f04ed30c1baa671798927d952f05400101f1118a/src/api/user.ts#L52)):*
> ```XML
>       }),
>     }),
>     verifyEmailAddress: build.mutation<
> ```

should this invalidate tags too?

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @faucomte97)

___
*[`src/api/klass.ts` line 26 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1#-NzYaUIoExwWY8Y6UpgI:-NzYri7x4LGGmAOq42MC:b-uakaxt) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/f04ed30c1baa671798927d952f05400101f1118a/src/api/klass.ts#L26)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Wanted to double check if `receive_requests_until` is in fact a required arg for creating a class. It looks like it is in the serializer, but are we planning to require teachers to provide this setting when creating a class? Default value currently is just "never" / "off"
</blockquote></details>

[It's not required though?](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4ac0b1f391052af79e5b8a17a7adb10cad655aae/backend/api/serializers/klass.py#L34-L35)
___
*[`src/api/schoolTeacherInvitation.ts` line 50 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1#-NzYpAnp0RWfUqatYwj1:-NzYs9nDBed52Lcmyltz:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/f04ed30c1baa671798927d952f05400101f1118a/src/api/schoolTeacherInvitation.ts#L50)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

add `/accept`
</blockquote></details>

Done.
___
*[`src/api/schoolTeacherInvitation.ts` line 61 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1#-NzYpJks2RuQpFGWmEhe:-NzYsA4F0mrmDllOnChm:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/f04ed30c1baa671798927d952f05400101f1118a/src/api/schoolTeacherInvitation.ts#L61)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

add `/reject`
</blockquote></details>

Done.
___
*[`src/api/user.ts` line 52 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1#-NzYq_O_Cso7SKMQ5kAK:-NzYsFWxEAz9abGXAAfl:b-cht7oy) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/f04ed30c1baa671798927d952f05400101f1118a/src/api/user.ts#L52)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

should this invalidate tags too?
</blockquote></details>

I don't think so.
When you list or retrieve users, they won't be included/excluded from the queryset depending on whether they have verified or not.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1#-:-NzYvd1z5tEsGYCoddpo:bnfp4nl)* status: all files reviewed, 2 unresolved discussions

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/1)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
