### PR TITLE
Auth flow

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4)* status: 0 of 53 files reviewed, 1 unresolved discussion

___
*[`package.json` line 23 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-flXvUDc1bOB0uCle0:-O-flXvUDc1bOB0uCle1:bnbocvi) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/62eaa3c5a8118b7d8e435bd67d5d91ff4c84e77f/package.json#L23)):*
> ```JSON
>   "//": "🚫 Don't add `dependencies` below that are inherited from the CFL package.",
>   "dependencies": {
>     "codeforlife": "github:ocadotechnology/codeforlife-package-javascript#auth_flow"
> ```

install new version

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4)* status: 0 of 53 files reviewed, 3 unresolved discussions

___
*[`src/pages/login/teacherForms/Email.tsx` line 35 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-frTk5Bh8ZGVT_8dXB:-O-frTk5Bh8ZGVT_8dXC:b-q3uach) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/62eaa3c5a8118b7d8e435bd67d5d91ff4c84e77f/src/pages/login/teacherForms/Email.tsx#L35)):*
> ```XML
>       })}
>     >
>       <form.EmailField helperText="Enter your email address" />
> ```

needs to be required
___
*[`src/pages/login/teacherForms/Email.tsx` line 36 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-frWQ38o6Jowg6scyf:-O-frWQ38o6Jowg6scyg:b-q3uach) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/62eaa3c5a8118b7d8e435bd67d5d91ff4c84e77f/src/pages/login/teacherForms/Email.tsx#L36)):*
> ```XML
>     >
>       <form.EmailField helperText="Enter your email address" />
>       <form.PasswordField helperText="Enter your password" />
> ```

needs to be required

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 50 of 53 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4)* status: 45 of 53 files reviewed, 20 unresolved discussions (waiting on @SKairinos)

___
*[`src/api/index.ts` line 53 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-ke-bS1oEfwEL3KLsf:-O-ke-bS1oEfwEL3KLsg:bb77ufx) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/api/index.ts#L53)):*
> ```XML
>       query: () => ({
>         url: "session/logout/",
>         method: "GET", // Should this be DELETE?
> ```

Yes?
___
*[`src/app/schemas.ts` line 26 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-kf2t8B_lDCSfem3tz:-O-kf2t8B_lDCSfem3u-:bibat29) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/app/schemas.ts#L26)):*
> ```XML
> })
> 
> // TODO: make indy password schema the same as teacher's.
> ```

No need for this TODO
___
*[`src/pages/login/IndyForm.tsx` line 31 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-kgGAXC51JjQJs7QqU:-O-kgGAXC51JjQJs7QqV:b-6rvccu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/IndyForm.tsx#L31)):*
> ```XML
>       })}
>     >
>       <form.EmailField required helperText="Enter your email address" />
> ```

remove helperText
___
*[`src/pages/login/IndyForm.tsx` line 32 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-kgHFqDDGRtbqUGs5_:-O-kgHFqDDGRtbqUGs5a:b-6rvccu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/IndyForm.tsx#L32)):*
> ```XML
>     >
>       <form.EmailField required helperText="Enter your email address" />
>       <form.PasswordField required helperText="Enter your password" />
> ```

remove helperText
___
*[`src/pages/login/studentForms/Class.tsx` line 74 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-kh6mTCeK0sDJhvk94:-O-kh6mTCeK0sDJhvk95:bz7gfe6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/studentForms/Class.tsx#L74)):*
> ```XML
>           <form.TextField
>             name="classId"
>             placeholder="Access code"
> ```

Update to start with "Enter your"
___
*[`src/pages/login/studentForms/Class.tsx` line 74 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-khDQl8GkbGXL6-lpr:-O-khDQl8GkbGXL6-lps:bd7k0in) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/studentForms/Class.tsx#L74)):*
> ```XML
>           <form.TextField
>             name="classId"
>             placeholder="Access code"
> ```

We need to be consistent between access code & class code. Current site says "class code" on this form (might say access code in other places tho)
___
*[`src/pages/login/studentForms/Class.tsx` line 75 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-khKYYDqn77wWqhwZS:-O-khKYZAHah5E43AaWY:b-cnyqum) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/studentForms/Class.tsx#L75)):*
> ```XML
>             name="classId"
>             placeholder="Access code"
>             helperText="Enter your access code"
> ```

Remove helperText
___
*[`src/pages/login/studentForms/Class.tsx` line 84 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-khOv53HOlTX7GuVyT:-O-khOv53HOlTX7GuVyU:bj8ahry) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/studentForms/Class.tsx#L84)):*
> ```XML
>           <Stack alignItems="end">
>             <form.SubmitButton endIcon={<ChevronRightIcon />}>
>               Next
> ```

Currently this says "Log in", did we decide back then to change it to "Next"?
___
*[`src/pages/login/studentForms/FirstName.tsx` line 64 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-khjJ-Bx5o-ArhJ_8-:-O-khjJ-Bx5o-ArhJ_80:b37ihcr) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/studentForms/FirstName.tsx#L64)):*
> ```XML
>         >
>           <form.FirstNameField
>             placeholder="Username"
> ```

Replace with "Enter your first name"
___
*[`src/pages/login/studentForms/FirstName.tsx` line 65 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-khlG66uUPgUrFOjJB:-O-khlG66uUPgUrFOjJC:bwrf3jc) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/studentForms/FirstName.tsx#L65)):*
> ```XML
>           <form.FirstNameField
>             placeholder="Username"
>             helperText="Enter your username"
> ```

Remove helper text
___
*[`src/pages/login/studentForms/FirstName.tsx` line 68 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-khnB3D57bPx8Vqugj:-O-khnB3D57bPx8Vqugk:b-cnyqum) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/studentForms/FirstName.tsx#L68)):*
> ```XML
>             required
>           />
>           <form.PasswordField helperText="Enter your password" required />
> ```

Remove helperText
___
*[`src/pages/login/teacherForms/Email.tsx` line 35 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-khxLb7b5apRkiICwt:-O-khxLb7b5apRkiICwu:b-cnyqum) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/teacherForms/Email.tsx#L35)):*
> ```XML
>       })}
>     >
>       <form.EmailField helperText="Enter your email address" />
> ```

Remove helperText
___
*[`src/pages/login/teacherForms/Email.tsx` line 36 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-khyjICWrhWf91Wimf:-O-khyjICWrhWf91Wimg:b-cnyqum) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/teacherForms/Email.tsx#L36)):*
> ```XML
>     >
>       <form.EmailField helperText="Enter your email address" />
>       <form.PasswordField helperText="Enter your password" />
> ```

Remove helperText
___
*[`src/pages/login/teacherForms/Otp.tsx` line 32 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-kiLYY2SlowSjQCnmW:-O-kiLYY2SlowSjQCnmX:bfwgax8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/teacherForms/Otp.tsx#L32)):*
> ```XML
>         })}
>       >
>         <form.OtpField helperText="Enter your code from your app" />
> ```

Switch helperText to placeholder
___
*[`src/pages/login/teacherForms/OtpBypassToken.tsx` line 24 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-kiW0q4eoXHgH46Ag_:-O-kiW0q4eoXHgH46Aga:bhe2su3) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/teacherForms/OtpBypassToken.tsx#L24)):*
> ```XML
>     <BaseForm
>       themedBoxProps={{ userType: "teacher" }}
>       header="Login as a teacher"
> ```

Inconsistency on the old website - update header to still say "Welcome"
___
*[`src/pages/login/teacherForms/OtpBypassToken.tsx` line 37 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-kipdT-UHhDwjqQSlC:-O-kipdT-UHhDwjqQSlD:b7qar92) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/teacherForms/OtpBypassToken.tsx#L37)):*
> ```XML
>         these backup tokens to login to your account.
>       </Typography>
>       <Typography fontWeight="bold">Token:</Typography>
> ```

Remove this - this should just be the label for the field below.
___
*[`src/pages/login/teacherForms/OtpBypassToken.tsx` line 40 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-kiyUa-d0RnUui05JZ:-O-kiyUa-d0RnUui05J_:bfwgax8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/teacherForms/OtpBypassToken.tsx#L40)):*
> ```XML
>       <form.TextField
>         name="token"
>         helperText="Enter one of your tokens"
> ```

Switch helperText to placeholder

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4)* status: all files reviewed, 6 unresolved discussions (waiting on @SKairinos)

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4)* status: all files reviewed, 4 unresolved discussions (waiting on @faucomte97)

___
*[`src/app/schemas.ts` line 26 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-kf2t8B_lDCSfem3tz:-O-kjru0A2Y7PC4Ccbv_:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/app/schemas.ts#L26)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

No need for this TODO
</blockquote></details>

Done.
___
*[`src/pages/login/studentForms/Class.tsx` line 74 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-khDQl8GkbGXL6-lpr:-O-kk4Bh2tDzbM8PCycP:b-nbxdek) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/studentForms/Class.tsx#L74)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

We need to be consistent between access code & class code. Current site says "class code" on this form (might say access code in other places tho)
</blockquote></details>

Agreed. Let's change to class code as it's more descriptive.
___
*[`src/pages/login/studentForms/Class.tsx` line 84 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-khOv53HOlTX7GuVyT:-O-kkSCtA-ugWiYuz1yj:bizhn1h) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/studentForms/Class.tsx#L84)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Currently this says "Log in", did we decide back then to change it to "Next"?
</blockquote></details>

Yes, since the button doesn't actually perform the "log in" action - just goes to the next step.
___
*[`src/pages/login/studentForms/FirstName.tsx` line 65 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-kjQa1Deq-0JiKDXIc:-O-kksLq8ZDwUKpv0z6r:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/5e8c040d01c8c5efa5c0017774fc78416629f258/src/pages/login/studentForms/FirstName.tsx#L65)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Replace with "Enter your first name"
</blockquote></details>

Done.
___
*[`src/pages/login/teacherForms/Otp.tsx` line 38 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-kjW741AUfz9ra4oot:-O-kkzko0Zk6Xi8W8t2E:bspj3) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/5e8c040d01c8c5efa5c0017774fc78416629f258/src/pages/login/teacherForms/Otp.tsx#L38)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Wonder if people will understand what this means?
</blockquote></details>

Perhaps we add a little quesion mark (hint) icon that says something like. "you were give 10 one-use tokens that you could use to bypass OTP authentication in case you ever last access to your authenticator app"?
___
*[`src/pages/login/teacherForms/OtpBypassToken.tsx` line 24 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-kiW0q4eoXHgH46Ag_:-O-klaFz2lKdhdxd0gNg:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/teacherForms/OtpBypassToken.tsx#L24)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Inconsistency on the old website - update header to still say "Welcome"
</blockquote></details>

Done.
___
*[`src/pages/login/teacherForms/OtpBypassToken.tsx` line 37 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4#-O-kipdT-UHhDwjqQSlC:-O-klr1J5bbSmUi3vYHj:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/c2e00b3178ecef5f22b2b4ca6269d82a4c2b442b/src/pages/login/teacherForms/OtpBypassToken.tsx#L37)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove this - this should just be the label for the field below.
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
