### PR TITLE
About us page

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29)

### CODE REVIEW

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29)* status: all files reviewed, 13 unresolved discussions (waiting on @faucomte97)

___
*[`.env` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3modEF7pq91Rh6HFBA:-O3modEF7pq91Rh6HFBB:b87x9er) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/.env#L12)):*
> ```Dotenv
> VITE_LINK_OUTLOOK_HOME=https://outlook.live.com/mail/
> VITE_LINK_SKILLS_FOR_THE_FUTURE=https://www.ocadogroup.com/sustainability/sustainability/
> VITE_LINK_PORTAL_GITHUB_HREF=https://github.com/ocadotechnology/codeforlife-portal
> ```

no need to append key with HREF since it's already prepended with LINK
___
*[`.env` line 13 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3moo8bAjS6fhCTXVuY:-O3moo8bAjS6fhCTXVuZ:b87x9er) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/.env#L13)):*
> ```Dotenv
> VITE_LINK_SKILLS_FOR_THE_FUTURE=https://www.ocadogroup.com/sustainability/sustainability/
> VITE_LINK_PORTAL_GITHUB_HREF=https://github.com/ocadotechnology/codeforlife-portal
> VITE_LINK_CFL_DOCS_HREF=https://docs.codeforlife.education/
> ```

no need to append key with HREF since it's already prepended with LINK
___
*[`src/pages/aboutUs/AboutUs.tsx` line 16 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mpFe-0NEhDzUdOKA9:-O3mpFe04DM48OoEI4Zc:bvtpy32) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/AboutUs.tsx#L16)):*
> ```XML
> 
> const AboutUs: FC<AboutUsProps> = () => {
>   const theme = useTheme()
> ```

delete this
___
*[`src/pages/aboutUs/AboutUs.tsx` line 34 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mpJz_1j-cWS2Y56cz:-O3mpJz_1j-cWS2Y56d-:b9usv2g) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/AboutUs.tsx#L34)):*
> ```XML
>         <Statistics />
>       </page.Section>
>       <page.Section boxProps={{ bgcolor: theme.palette.info.main }}>
> ```

use short hand `bgcolor: "info.main"`
___
*[`src/pages/aboutUs/AboutUs.tsx` line 40 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mpPaOBVcCZKsVLlbN:-O3mpPaOBVcCZKsVLlbO:b9usv2g) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/AboutUs.tsx#L40)):*
> ```XML
>         <OcadoGroup />
>       </page.Section>
>       <page.Section boxProps={{ bgcolor: theme.palette.info.main }}>
> ```

use short hand `bgcolor: "info.main"`
___
*[`src/pages/aboutUs/AboutUs.tsx` line 46 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mpQ5J6rLXTYumw6Hf:-O3mpQ5J6rLXTYumw6Hg:b9usv2g) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/AboutUs.tsx#L46)):*
> ```XML
>         <Supporters />
>       </page.Section>
>       <page.Section boxProps={{ bgcolor: theme.palette.info.main }}>
> ```

use short hand `bgcolor: "info.main"`
___
*[`src/pages/aboutUs/Quotes.tsx` line 4 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mqGaW2pfeKZPQon48:-O3mqGaW2pfeKZPQon49:bm8gtrb) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Quotes.tsx#L4)):*
> ```XML
> import { type FC } from "react"
> 
> export interface QuoteProps {
> ```

don't export this since we're not exporting Quote. Can also define the props directly in FC if you want.
___
*[`src/pages/aboutUs/Statistics.tsx` line 4 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mqtq88nYCvy5TMUB7:-O3mqtq88nYCvy5TMUB8:bbx3fpv) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Statistics.tsx#L4)):*
> ```XML
> import { type FC } from "react"
> 
> export interface StatisticProps {
> ```

don't export this since we're not exporting Statistic. Can also define the props directly in FC if you want.
___
*[`src/pages/aboutUs/Supporters.tsx` line 4 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mr6j3AuD7NnNgSCFe:-O3mr6j3AuD7NnNgSCFf:bv161rv) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L4)):*
> ```XML
> import { type FC } from "react"
> 
> import { Image } from "codeforlife/components"
> ```

import should be with above import group
___
*[`src/pages/aboutUs/Supporters.tsx` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mrD7v5reL4CpeLRVx:-O3mrD7v5reL4CpeLRVy:b-lwg9j6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L15)):*
> ```XML
> import PressureCookerImage from "../../images/pressure_cooker_logo.png"
> 
> export interface SupporterProps {
> ```

see previous comment. don't export
___
*[`src/pages/aboutUs/Supporters.tsx` line 56 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mn4HRDRD58g8-S_GM:-O3mn4HRDRD58g8-S_GN:bckr7wr) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L56)):*
> ```XML
>             To contribute, head over to{" "}
>             <Link
>               href={import.meta.env.VITE_LINK_PORTAL_GITHUB_HREF}
> ```

now that we've improved our docs, this should link to https://docs.codeforlife.education/become-a-contributor
___
*[`src/pages/aboutUs/Supporters.tsx` line 56 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mnGC0DPsn7Hu5kMAN:-O3mnGC0DPsn7Hu5kMAO:b-y7iqzc) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L56)):*
> ```XML
>             To contribute, head over to{" "}
>             <Link
>               href={import.meta.env.VITE_LINK_PORTAL_GITHUB_HREF}
> ```

use to property, not href
___
*[`src/pages/aboutUs/Supporters.tsx` line 67 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mrY0b2dbFnmT4Fd7K:-O3mrY0c5XtbKv9gpL1N:b-y7iqzc) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L67)):*
> ```XML
>             find more info about how to do all these on our{" "}
>             <Link
>               href={import.meta.env.VITE_LINK_CFL_DOCS_HREF}
> ```

use to property, not href

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29)* status: all files reviewed, 13 unresolved discussions (waiting on @SKairinos)

___
*[`.env` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3modEF7pq91Rh6HFBA:-O3nup9z96yLOSC4V3XM:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/.env#L12)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

no need to append key with HREF since it's already prepended with LINK
</blockquote></details>

Done.
___
*[`.env` line 13 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3moo8bAjS6fhCTXVuY:-O3nupMG1yvEvCnFuegE:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/.env#L13)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

no need to append key with HREF since it's already prepended with LINK
</blockquote></details>

Done.
___
*[`src/pages/aboutUs/AboutUs.tsx` line 16 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mpFe-0NEhDzUdOKA9:-O3nv-0k-MBx-F7M7-le:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/AboutUs.tsx#L16)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

delete this
</blockquote></details>

Done.
___
*[`src/pages/aboutUs/AboutUs.tsx` line 34 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mpJz_1j-cWS2Y56cz:-O3nv-Et67qpbRAc1jnw:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/AboutUs.tsx#L34)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

use short hand `bgcolor: "info.main"`
</blockquote></details>

Done.
___
*[`src/pages/aboutUs/AboutUs.tsx` line 40 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mpPaOBVcCZKsVLlbN:-O3nv-YOEexpouNJc2Vr:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/AboutUs.tsx#L40)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

use short hand `bgcolor: "info.main"`
</blockquote></details>

Done.
___
*[`src/pages/aboutUs/AboutUs.tsx` line 46 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mpQ5J6rLXTYumw6Hf:-O3nv-mC7w5zsXSx6P57:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/AboutUs.tsx#L46)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

use short hand `bgcolor: "info.main"`
</blockquote></details>

Done.
___
*[`src/pages/aboutUs/Quotes.tsx` line 4 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mqGaW2pfeKZPQon48:-O3nv94l4Z-q0J9qFniC:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Quotes.tsx#L4)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

don't export this since we're not exporting Quote. Can also define the props directly in FC if you want.
</blockquote></details>

Done.
___
*[`src/pages/aboutUs/Statistics.tsx` line 4 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mqtq88nYCvy5TMUB7:-O3nvCeK9mWOlFQiSNzN:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Statistics.tsx#L4)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

don't export this since we're not exporting Statistic. Can also define the props directly in FC if you want.
</blockquote></details>

Done.
___
*[`src/pages/aboutUs/Supporters.tsx` line 4 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mr6j3AuD7NnNgSCFe:-O3nvI5rCGZaqwhztaxe:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L4)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

import should be with above import group
</blockquote></details>

Done.
___
*[`src/pages/aboutUs/Supporters.tsx` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mrD7v5reL4CpeLRVx:-O3nvOID0rpanwYA1Rmr:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L15)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

see previous comment. don't export
</blockquote></details>

Done.
___
*[`src/pages/aboutUs/Supporters.tsx` line 56 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mn4HRDRD58g8-S_GM:-O3nvTQz88dqj6MgVx20:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L56)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

now that we've improved our docs, this should link to https://docs.codeforlife.education/become-a-contributor
</blockquote></details>

Done.
___
*[`src/pages/aboutUs/Supporters.tsx` line 56 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mnGC0DPsn7Hu5kMAN:-O3nw77fAAbizWrhoX75:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L56)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

use to property, not href
</blockquote></details>

Done.
___
*[`src/pages/aboutUs/Supporters.tsx` line 67 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mrY0b2dbFnmT4Fd7K:-O3nw7X92acV7PZxNLWh:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L67)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

use to property, not href
</blockquote></details>

Done.

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29)* status: all files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[`src/pages/aboutUs/Supporters.tsx` line 56 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mnGC0DPsn7Hu5kMAN:-O3ptl8wBUMejC-ERFvA:b-4y30lu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L56)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why did you delete the color and underline props?
___
*[`src/pages/aboutUs/Supporters.tsx` line 67 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mrY0b2dbFnmT4Fd7K:-O3ptsfl1vkrgj7GS649:b-4y30lu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L67)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why did you delete the color and underline props?
___
*[`src/pages/aboutUs/Supporters.tsx` line 3 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3psub65M_IOJJXVZ8_:-O3psub65M_IOJJXVZ8a:b-3cnvie) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/d6bfc1c72bac8909a89cb44bf9297d00a9fd644b/src/pages/aboutUs/Supporters.tsx#L3)):*
> ```XML
> import {
>   Unstable_Grid2 as Grid,
>   Link as MuiLink,
> ```

don't use MuiLink, just use our Link

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @SKairinos)

___
*[`src/pages/aboutUs/Supporters.tsx` line 56 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mnGC0DPsn7Hu5kMAN:-O45RciiCmW7NWOvB1dP:b-ghhamf) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L56)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why did you delete the color and underline props?
</blockquote></details>

Because none of the other Links we use have those props so I assume we don't want them
___
*[`src/pages/aboutUs/Supporters.tsx` line 67 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mrY0b2dbFnmT4Fd7K:-O45RgYK99B34geaC1-N:b-ghhamf) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L67)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why did you delete the color and underline props?
</blockquote></details>

Because none of the other Links we use have those props so I assume we don't want them
___
*[`src/pages/aboutUs/Supporters.tsx` line 3 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3psub65M_IOJJXVZ8_:-O45RcGK2RzrAs_RHLEJ:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/d6bfc1c72bac8909a89cb44bf9297d00a9fd644b/src/pages/aboutUs/Supporters.tsx#L3)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

don't use MuiLink, just use our Link
</blockquote></details>

Done.

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`src/pages/aboutUs/Supporters.tsx` line 56 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mnGC0DPsn7Hu5kMAN:-O45VpFT6TH1nI_0WfhP:b61tm36) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L56)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Because none of the other Links we use have those props so I assume we don't want them
</blockquote></details>

In this case we do. Otherwise the text would like normal typography, not a link. ([see on the old site](https://www.codeforlife.education/about))
___
*[`src/pages/aboutUs/Supporters.tsx` line 67 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mrY0b2dbFnmT4Fd7K:-O45W6U7AwpilABMr0fJ:b61tm36) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L67)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Because none of the other Links we use have those props so I assume we don't want them
</blockquote></details>

In this case we do. Otherwise the text would like normal typography, not a link. ([see on the old site](https://www.codeforlife.education/about))

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`src/pages/aboutUs/Supporters.tsx` line 56 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mnGC0DPsn7Hu5kMAN:-O45WD0gDI17czkEU9en:btx7894) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L56)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

In this case we do. Otherwise the text would like normal typography, not a link. ([see on the old site](https://www.codeforlife.education/about))
</blockquote></details>

*would look like
___
*[`src/pages/aboutUs/Supporters.tsx` line 67 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mrY0b2dbFnmT4Fd7K:-O45W9U99cBSfcIZX3KH:btx7894) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L67)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

In this case we do. Otherwise the text would like normal typography, not a link. ([see on the old site](https://www.codeforlife.education/about))
</blockquote></details>

*would look like

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29)* status: all files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`src/pages/aboutUs/Supporters.tsx` line 56 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mnGC0DPsn7Hu5kMAN:-O45Zh0h8c7dNhH58Vpy:bnbutbj) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L56)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

*would look like
</blockquote></details>

No, they still have the underline


___
*[`src/pages/aboutUs/Supporters.tsx` line 67 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29#-O3mrY0b2dbFnmT4Fd7K:-O45Zj66BNaJqPXZdr3W:bknfsgr) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-frontend/blob/07c86ca8875a8cb65996498cb42f754d9070a7c9/src/pages/aboutUs/Supporters.tsx#L67)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

*would look like
</blockquote></details>

**Review by SKairinos — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-frontend/29)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
